version: '3.7'
services:
  docker:
    container_name: docker
    build: docker
    ports:
      - "9000:8000"
    volumes:
      - ./:/var/www/

  mailer:
    container_name: mailer
    image: schickling/mailcatcher
    ports: [ "1025", "1080" ]

  database:
    container_name: mysql
    image: 'mysql:8.0.27'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
#  database:
#    container_name: database_postgre
#    image: postgres:13-alpine
#    environment:
#      POSTGRES_DB: serve_me
#      POSTGRES_PASSWORD:
#      POSTGRES_USER: mehdi
#    volumes:
#      - db-data:/var/lib/postgresql/data:rw
#    ports:
#      - "5432"

volumes:
  db-data:
