version: "3.7"
services:
  docker:
    container_name: docker
    build: docker
    ports:
      - "9000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - dev

  mailer:
    container_name: mailer
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
    networks:
      - dev

  database:
    container_name: mysql
    image: "mysql:8.0.27"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - dev

networks:
  dev:
